ci-cd:
  - .github/**/*

dependencies:
  - cmake/**/*

documentation:
  - docs/**/*

enhancement:
  - src/**/*
  - include/**/*

quality:
  - tests/**/*

tooling:
  - CMakeLists.txt
  - config.h.in
  - '**/CMakeLists.txt'
