var searchData=
[
  ['l2y_312',['l2y',['../classImage.html#a28c2182458e5c03bf03d4f486f88c9e7',1,'Image']]],
  ['lanczos_313',['Lanczos',['../classLanczos.html',1,'']]],
  ['legendurl_314',['LegendURL',['../classLegendURL.html',1,'LegendURL'],['../classLegendURL.html#aadcd1afb1f54b69af6ada33009ed809f',1,'LegendURL::LegendURL(json11::Json doc)'],['../classLegendURL.html#ad6d24f8db116d685ed77935b95f290c5',1,'LegendURL::LegendURL(const LegendURL &amp;origLUrl)']]],
  ['legendurl_2eh_315',['LegendURL.h',['../LegendURL_8h.html',1,'']]],
  ['level_316',['Level',['../classLevel.html',1,'']]],
  ['libcurlstruct_2eh_317',['LibcurlStruct.h',['../LibcurlStruct_8h.html',1,'']]],
  ['libjpegimage_318',['LibjpegImage',['../classLibjpegImage.html',1,'LibjpegImage'],['../classLibjpegImage.html#a937a712ec1732cd3048a13c187de9761',1,'LibjpegImage::LibjpegImage()']]],
  ['libjpegimage_2ecpp_319',['LibjpegImage.cpp',['../LibjpegImage_8cpp.html',1,'']]],
  ['libjpegimage_2eh_320',['LibjpegImage.h',['../LibjpegImage_8h.html',1,'']]],
  ['libjpegimagefactory_321',['LibjpegImageFactory',['../classLibjpegImageFactory.html',1,'']]],
  ['libkakaduimage_322',['LibkakaduImage',['../classLibkakaduImage.html',1,'LibkakaduImage'],['../classLibkakaduImage.html#a3c809c31e07d420c70022441695ce48e',1,'LibkakaduImage::LibkakaduImage()']]],
  ['libkakaduimage_2ecpp_323',['LibkakaduImage.cpp',['../LibkakaduImage_8cpp.html',1,'']]],
  ['libkakaduimage_2eh_324',['LibkakaduImage.h',['../LibkakaduImage_8h.html',1,'']]],
  ['libkakaduimagefactory_325',['LibkakaduImageFactory',['../classLibkakaduImageFactory.html',1,'']]],
  ['libopenjpegimage_326',['LibopenjpegImage',['../classLibopenjpegImage.html',1,'LibopenjpegImage'],['../classLibopenjpegImage.html#a953fbfd5a823995579554b397df61d09',1,'LibopenjpegImage::LibopenjpegImage()']]],
  ['libopenjpegimage_2ecpp_327',['LibopenjpegImage.cpp',['../LibopenjpegImage_8cpp.html',1,'']]],
  ['libopenjpegimage_2eh_328',['LibopenjpegImage.h',['../LibopenjpegImage_8h.html',1,'']]],
  ['libopenjpegimagefactory_329',['LibopenjpegImageFactory',['../classLibopenjpegImageFactory.html',1,'']]],
  ['libpngimage_330',['LibpngImage',['../classLibpngImage.html',1,'LibpngImage'],['../classLibpngImage.html#a89b1e30e029fa660f73e321b1d98d139',1,'LibpngImage::LibpngImage()']]],
  ['libpngimage_2ecpp_331',['LibpngImage.cpp',['../LibpngImage_8cpp.html',1,'']]],
  ['libpngimage_2eh_332',['LibpngImage.h',['../LibpngImage_8h.html',1,'']]],
  ['libpngimagefactory_333',['LibpngImageFactory',['../classLibpngImageFactory.html',1,'']]],
  ['libtiffimage_334',['LibtiffImage',['../classLibtiffImage.html',1,'LibtiffImage'],['../classLibtiffImage.html#a0e97f77431ce656939b333f68db289c5',1,'LibtiffImage::LibtiffImage(int width, int height, double resx, double resy, int ch, BoundingBox&lt; double &gt; bbox, std::string name, SampleFormat::eSampleFormat sampleformat, int bitspersample, Photometric::ePhotometric photometric, Compression::eCompression compression, TIFF *tif, int rowsperstrip, ExtraSample::eExtraSample esType=ExtraSample::ALPHA_UNASSOC)'],['../classLibtiffImage.html#a1825bd285faf49531d54237d169743fc',1,'LibtiffImage::LibtiffImage(int width, int height, double resx, double resy, int ch, BoundingBox&lt; double &gt; bbox, std::string name, int sf, int bps, int ph, int comp, TIFF *tif, int rowsperstrip, ExtraSample::eExtraSample esType=ExtraSample::ALPHA_UNASSOC, bool tiled=false, bool palette=false)']]],
  ['libtiffimage_2ecpp_335',['LibtiffImage.cpp',['../LibtiffImage_8cpp.html',1,'']]],
  ['libtiffimage_2eh_336',['LibtiffImage.h',['../LibtiffImage_8h.html',1,'']]],
  ['libtiffimagefactory_337',['LibtiffImageFactory',['../classLibtiffImageFactory.html',1,'']]],
  ['line_338',['Line',['../classLine.html',1,'Line'],['../classLine.html#a03de805a8450555db46461577dea0f7f',1,'Line::Line(int width, int samplesize)'],['../classLine.html#a412d63b26cf01432b5a2de7c42437d55',1,'Line::Line(T *imageIn, uint8_t *maskIn, int srcSpp, int width, T *transparent)'],['../classLine.html#a603dca1fc5d38527ceadf87dad32fb61',1,'Line::Line(T *imageIn, uint8_t *maskIn, int srcSpp, int width)']]],
  ['line_2eh_339',['Line.h',['../Line_8h.html',1,'']]],
  ['linear_340',['Linear',['../classLinear.html',1,'']]],
  ['lzwdecoder_341',['LzwDecoder',['../structLzwDecoder.html',1,'LzwDecoder'],['../classlzwDecoder.html',1,'lzwDecoder']]],
  ['lzwencoder_342',['lzwEncoder',['../classlzwEncoder.html',1,'']]],
  ['liste_20des_20choses_20à_20faire_343',['Liste des choses à faire',['../todo.html',1,'']]]
];
